"use client";
import { FileText, Download, X, AlertTriangle } from 'lucide-react';
import './AuditLog.css';

export default function AuditLog({ session, utterances, onClose }) {
  if (!session) return null;

  const duration = session.completedAt
    ? Math.round((session.completedAt - session.startedAt) / 1000)
    : Math.round((Date.now() - session.startedAt) / 1000);

  const formatDuration = (secs) => {
    const m = Math.floor(secs / 60);
    const s = secs % 60;
    return `${m}m ${s}s`;
  };

  const flaggedCount = utterances.filter(u => u.flagged).length;
  const allTags = [...new Set(utterances.flatMap(u => u.medicalTags || []))];

  const handleExport = () => {
    const lines = [];
    lines.push('INTERP — COMPLIANCE RECORD');
    lines.push('═'.repeat(50));
    lines.push('');
    lines.push(`Session ID: ${session.id}`);
    lines.push(`Date: ${new Date(session.startedAt).toLocaleString()}`);
    lines.push(`Duration: ${formatDuration(duration)}`);
    lines.push(`Language Pair: ${session.physicianLang.toUpperCase()} ↔ ${session.patientLang.toUpperCase()}`);
    lines.push(`Encounter: ${session.encounterType}`);
    lines.push(`Exchanges: ${utterances.length}`);
    lines.push(`Avg Accuracy: ${Math.round(session.avgAccuracy)}%`);
    lines.push(`Avg Comprehension: ${Math.round(session.avgComprehension)}%`);
    lines.push(`Flagged: ${flaggedCount}`);
    lines.push(`Medical Tags: ${allTags.map(t => '@' + t).join(', ') || 'None'}`);
    if (session.escalatedAt) {
      lines.push(`ESCALATED: ${new Date(session.escalatedAt).toLocaleString()}`);
      lines.push(`Reason: ${session.escalationReason}`);
    }
    lines.push('');
    lines.push('─'.repeat(50));
    lines.push('TRANSCRIPT');
    lines.push('─'.repeat(50));
    lines.push('');

    utterances.forEach((u, i) => {
      const time = new Date(u.timestamp).toLocaleTimeString();
      lines.push(`[${time}] ${u.role.toUpperCase()} (${u.sourceLang}→${u.targetLang})`);
      lines.push(`  Original: ${u.originalText}`);
      if (u.translatedText) lines.push(`  Translated: ${u.translatedText}`);
      if (u.backTranslation) lines.push(`  Back-translation: ${u.backTranslation}`);
      if (u.accuracyScore !== null) lines.push(`  Accuracy: ${Math.round(u.accuracyScore)}% | Comprehension: ${Math.round(u.comprehensionScore)}%`);
      if (u.medicalTags?.length) lines.push(`  Tags: ${u.medicalTags.map(t => '@' + t).join(', ')}`);
      if (u.flagged) lines.push(`  ⚠ FLAGGED: ${u.flagReason || 'Review required'}`);
      if (u.interpreterCorrected) lines.push(`  ⚑ INTERPRETER CORRECTED`);
      if (u.comprehensionCheck) {
        const cc = u.comprehensionCheck;
        lines.push(`  Comprehension Check: ${cc.status.toUpperCase()}`);
        if (cc.question) lines.push(`    Question: ${cc.question}`);
        if (cc.patientResponse) lines.push(`    Patient Response: ${cc.patientResponse}`);
        if (cc.status === 'fail' && cc.simplifiedVersion) lines.push(`    Suggested Rephrasing: ${cc.simplifiedVersion}`);
      }
      lines.push('');
    });

    lines.push('─'.repeat(50));
    lines.push('Generated by Interp — Patent Pending');
    lines.push(`Exported: ${new Date().toLocaleString()}`);

    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `interp-session-${session.id}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="audit-overlay" onClick={onClose}>
      <div className="audit-panel" onClick={(e) => e.stopPropagation()}>
        <div className="audit-header">
          <div className="audit-header__left">
            <FileText size={18} />
            <h2>Compliance Record</h2>
          </div>
          <div className="audit-header__right">
            <button className="audit-export" onClick={handleExport}>
              <Download size={14} />
              Export
            </button>
            <button className="audit-close" onClick={onClose}>
              <X size={18} />
            </button>
          </div>
        </div>

        <div className="audit-summary">
          <div className="audit-stat">
            <span className="audit-stat__label">Duration</span>
            <span className="audit-stat__value">{formatDuration(duration)}</span>
          </div>
          <div className="audit-stat">
            <span className="audit-stat__label">Exchanges</span>
            <span className="audit-stat__value">{utterances.length}</span>
          </div>
          <div className="audit-stat">
            <span className="audit-stat__label">Avg Accuracy</span>
            <span className="audit-stat__value">{Math.round(session.avgAccuracy || 0)}%</span>
          </div>
          <div className="audit-stat">
            <span className="audit-stat__label">Avg Comprehension</span>
            <span className="audit-stat__value">{Math.round(session.avgComprehension || 0)}%</span>
          </div>
          {flaggedCount > 0 && (
            <div className="audit-stat audit-stat--flagged">
              <span className="audit-stat__label">Flagged</span>
              <span className="audit-stat__value">{flaggedCount}</span>
            </div>
          )}
        </div>

        {allTags.length > 0 && (
          <div className="audit-tags">
            {allTags.map(tag => (
              <span key={tag} className={`audit-tag audit-tag--${tag}`}>@{tag}</span>
            ))}
          </div>
        )}

        <div className="audit-transcript">
          {utterances.map((u, i) => (
            <div key={u.id} className={`audit-entry ${u.flagged ? 'audit-entry--flagged' : ''}`}>
              <div className="audit-entry__header">
                <span className="audit-entry__num">#{i + 1}</span>
                <span className={`audit-entry__role audit-entry__role--${u.role}`}>
                  {u.role}
                </span>
                <span className="audit-entry__time">
                  {new Date(u.timestamp).toLocaleTimeString()}
                </span>
                {u.accuracyScore !== null && (
                  <span className={`audit-entry__score ${u.comprehensionScore >= 85 ? 'good' : u.comprehensionScore >= 60 ? 'warn' : 'poor'}`}>
                    {Math.round(u.comprehensionScore)}%
                  </span>
                )}
                {u.flagged && <AlertTriangle size={12} className="audit-entry__flag" />}
              </div>
              <p className="audit-entry__text">{u.originalText}</p>
              {u.translatedText && (
                <p className="audit-entry__translated">{u.translatedText}</p>
              )}
              {u.interpreterCorrected && (
                <span className="audit-entry__corrected">interpreter-corrected</span>
              )}
              {u.comprehensionCheck && u.comprehensionCheck.status !== 'pending' && (
                <div className={`audit-entry__check audit-entry__check--${u.comprehensionCheck.status}`}>
                  Check: {u.comprehensionCheck.status}
                  {u.comprehensionCheck.question ? ` — ${u.comprehensionCheck.question}` : ''}
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
